INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Agrippastraße 158');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ahler Straße 72');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Alstedder Straße 50');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Alte Vallendarer Straße 5');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Altenhäuser Straße 38');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Althoffstraße 11');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Alten Friedhof 105');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Dorn 38');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Krummen Acker 99');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Laach 121 c');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Nörrenpfad 160');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Am Taubenbaum80');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'An Kuckum 46');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Aspelerstraße 64');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Auf dem Gäu 185');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Auf dem Hähnchen 83');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Auf dem Nippes 61');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Aufm Stück 113');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bellerwiese 168');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bellerwiese 170');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bertrodtstraße 137');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Beuthener Straße 98');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bickenbachstraße 128');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Biehlstraße 91');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bornweg 180 a');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Breehegge 106');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Breite Straße 89');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Breitwiesenstraße 58');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Breniger Straße 104');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Brentanostraße 126');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Britzinger Straße19');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bungertstraße 131');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Bökelstraße 65');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Carlstraße 18');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Charlottenstraße 88');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Cheruskerstraße 97');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Clemens-August-Straße 198');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Damiansweg 194');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Dauner Straße 58');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Dilborner Straße 77');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Düesbergweg 26');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ebertstraße 50');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Eichenstraße 90');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Eidamshauser Straße 61');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Eisenhardtstraße 63');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Elsetalstraße 143 c');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Emsdettener Straße 160');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Enger Weg 121');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Erdinger Straße58');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Erftstraße 28');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Erikaweg 15');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ettringer Straße 148');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Faggenwinkel 20');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ferdinand-Lassalle-Straße 71');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Forstweide 120');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Franz-Sellhorst-Straße 138');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Freienfels 125');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Freienfels 149');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Fresnostraße 127');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Frühmesserstraße 115');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Fürstenweg 71');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Gabelsberger Straße 96');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Geißäckerstraße 68');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Geraer Straße 140');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Goerdelerstraße 141');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Goldbäumchenstraße 116');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Gustav-Heinemann-Ring 80');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hachener Straße 6');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hafenstraße 178');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Haigerer Straße 74');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hannebacher Straße 27');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hartmannstraße 118');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hartmannstraße 190');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Heidenstraße 124');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Heiligenhausstraße 151');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Helbecker Weg 71');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Herberner Straße 47');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hermann-Treff-Weg 122');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hetzert 155');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hindenburgplatz 46');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hirschberger Straße 123 c');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hofpfad 134');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hohler Weg 192');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Horresser Straße 195');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hubaleck-Siedlung 187');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Hugo-Mueller-Straße 34 a');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Eichholz 196');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Glockenschall 4');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Lustgarten 140');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Rahlert 34');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Schönblick 35 b');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Im Überdorf 174');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'In den Heilgärten 166');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'In der Aach53');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'In der Betz 133');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Joachimstraße 89 a');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Johannesweg48');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kalteborn 124');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kanalweg 16');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kapellenkamp 171');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kehriger Straße 27');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Keltenweg 25');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Keltrisstraße 49');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kerpener Straße 198');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kirchbergstraße 136');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Klinkkampweg 107');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Klottengasse 117');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Koberner Weg 129');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Koblenz-Olper-Straße 190');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Krautsgasse 136');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kreuzberg 48');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Krokusstraße 173');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Krokusweg 74');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kuhlenkamp 106');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Kömpchen 70');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lange Hecke 192');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lerchenhain 111');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lerchenhain 79');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Libellenweg 129');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lindenplatz 130');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lippeweg 199');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Lippweg 45');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ludwig-Uhland-Straße 5');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Löh 99');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Marienweg 127');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Markstraße 180');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Massonneaustraße 188');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Masurenweg 73');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Miesenheimer Straße 178');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Mommkamp 62');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Mühlenbrey 120');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Mühlweg 178 c');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Neue Reihe 145');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Neuenhammstraße 154');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Nieper Straße 161');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Nonnenbacher Weg 59');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Oberer Weg 177');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Offerkämpe 153');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Offerkämpe 8');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ostheldener Straße 78');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Pantaleonstraße 50');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Pastors Kamp 80');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Pehrstraße 148');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Pfaffenacker 84');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Pottumer Straße 75');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Rahmstraße 177');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Raiffeisenstraße 142');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Rammelberg 78');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Roggenkamp 186');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Rosenstraße 156');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Rostesiepen 104');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Römerring 22');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Samberg 115');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Sauerbruchstraße 123');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Scheidter Straße 178');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Schleiermacherstraße 147c');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Schmiedestraße 34');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Schneckenhofengasse 19');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Schwanenweg 44');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Schweitzerstraße 66');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Siersdorfer Straße 90');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Silberstraße 131');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Spiekersstraße 63');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'St.-Josef-Straße 102');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Stadtveener Straße 32');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Steimeler Straße 160');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Steinbörnchenweg 26');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Steinerbergstraße 138');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Straßburger Straße 171');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Studtstraße99');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Sudfeldstraße 40');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Südring 45');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Talweg 24');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Temming 136');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Tetendonk 194');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Tiefental195');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Uferplatz177');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Ulmtalstraße 198');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Von-Oppenheim-Straße 75');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Von-der-Leyen-Straße 142');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wallheckenweg 179');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Walramstraße 34');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wehrer Straße 62');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wehrer Straße 80');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Weihersbergstraße 114');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Weinbergstraße 122');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Weißer Berg33');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wenzelstraße 100');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Westfalenring 45 a');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wetkampstraße 153');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Weyerstraße 71');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wiedhöhe 59');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wildenburg-Bahnhof 68');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Wolfgangstraße 117');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zeppelinstraße48');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zum Acker 87');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zur Hardt 154');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zur Vogelstange 151');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zur alten Burg 15 a');
INSERT INTO Strassen (StrOID,Strasse) VALUES (NULL,'Zweite Straße 77');